### ISSUE TITLE
Full playlist not downloading in Ubuntu

### ISSUE THREAD

**Issue by vikku04** [amitjoshi9627/WolfTube#8]
While trying to download the full playlist again some errors are occurring. Please look onto it. I am also attaching a screenshot of the issue.

![AJ](https://user-images.githubusercontent.com/39962694/72675682-07ee4e00-3aae-11ea-832b-ca1ea782a83b.jpg)

**Comment by amitjoshi9627** [comment]
This Issue has beed resolved Thus I am closing the Issue now.
